services:
  nr-relay:
    build:
      context: ..
      dockerfile: env-tests/Dockerfile
    hostname: reaper
    command: python3 /agents/nullrelay.py
    environment:
      WORKER_URL: http://host.docker.internal:8787
      C2_PSK: testkey123
      C2_INT: "1"
      C2_JITTER: "1"
      C2_RELAY_PORT: "8443"
      USER: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  nr-isolated:
    build:
      context: ..
      dockerfile: env-tests/Dockerfile
    hostname: phantom
    command: python3 /agents/nullrelay.py
    environment:
      WORKER_URL: http://nr-relay:8443
      C2_PSK: testkey123
      C2_INT: "1"
      C2_JITTER: "1"
      USER: root
    restart: on-failure
    depends_on:
      - nr-relay

  nr-direct:
    build:
      context: ..
      dockerfile: env-tests/Dockerfile
    hostname: ghost
    command: python3 /agents/nullrelay.py
    environment:
      WORKER_URL: http://host.docker.internal:8787
      C2_PSK: testkey123
      C2_INT: "1"
      C2_JITTER: "1"
      USER: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  nr-dead:
    build:
      context: ..
      dockerfile: env-tests/Dockerfile
    hostname: shade
    command: sh -c "python3 /agents/nullrelay.py & sleep 5; kill %1"
    environment:
      WORKER_URL: http://host.docker.internal:8787
      C2_PSK: testkey123
      C2_INT: "1"
      C2_JITTER: "1"
      USER: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"

  cv-relay:
    build:
      context: ..
      dockerfile: env-tests/Dockerfile
    hostname: wraith
    command: python3 /agents/clockvenom.py
    environment:
      C2_PSK: testkey123
      C2_INT: "1"
      C2_JITTER: "1"
      C2_DIRECT: host.docker.internal
      C2_NTP_RELAY_PORT: "123"
      C2_NTP_RELAY_TARGET: host.docker.internal:443
      USER: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  cv-isolated:
    build:
      context: ..
      dockerfile: env-tests/Dockerfile
    hostname: specter
    command: python3 /agents/clockvenom.py
    environment:
      C2_PSK: testkey123
      C2_INT: "1"
      C2_JITTER: "1"
      C2_DIRECT: cv-relay
      USER: root
    restart: on-failure
    depends_on:
      - cv-relay

  cv-direct:
    build:
      context: ..
      dockerfile: env-tests/Dockerfile
    hostname: venom
    command: python3 /agents/clockvenom.py
    environment:
      C2_PSK: testkey123
      C2_INT: "1"
      C2_JITTER: "1"
      C2_DIRECT: host.docker.internal
      USER: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
